#!/bin/bash

# ensure sudo user
if [ "$(whoami)" != "root" ] ; then
        echo "Error: This script requires 'sudo' privileges in order to write to disk & mount media."
        exit 1
fi

echo
echo "= This will update U-Boot and the "
echo "= Raspberry Pi Firmware to the latest."
UBOOT=$(rpm -q uboot-images-armv7)
if [ "$UBOOT" = "package uboot-images-armv7 is not installed" ]; then
        echo
        echo "$UBOOT"
        read -p "Would you like to install uboot-images-armv7 (yes or no)? " INSTALL_UBOOT
        if [ "$(echo ${INSTALL_UBOOT} | tr [:lower:] [:upper:])" = "YES" ] ; thee
n
        dnf install -y uboot-images-armv7
        UBOOT=$(rpm -q uboot-images-armv7)
        fi
fi
FW=$(rpm -q bcm283x-firmware)
if [ "$FW" = "package bcm283x-firmware is not installed" ]; then
        echo
        echo "$FW"
        read -p "Would you like to install bcm283x-firmware (yes or no)? " INSTALL_FW
        if [ "$(echo ${INSTALL_FW} | tr [:lower:] [:upper:])" = "YES" ] ; then
                dnf install -y bcm283x-firmware
                FW=$(rpm -q bcm283x-firmware)
        fi
fi
echo
echo "= Uboot: $UBOOT"
echo "= Firmware: $FW"
if [ -d /boot/fw ]; then
        	mount /dev/mmcblk0p1 /boot/fw
        else
        	mkdir /boot/fw
        	mount /dev/mmcblk0p1 /boot/fw
fi
# copy uboot
if [ -f /usr/share/uboot/rpi_2/u-boot.bin ]; then
        cp -rp /usr/share/uboot/rpi_2/u-boot.bin /boot/fw/rpi2-u-boot.bin
        else
        echo "Missing U-Boot for Raspberry Pi 2, no file copied."
fi
if [ -f /usr/share/uboot/rpi_3_32b/u-boot.bin ]; then
        cp -rp /usr/share/uboot/rpi_3_32b/u-boot.bin /boot/fw/rpi3-u-boot.bin
        else
        echo "Missing U-Boot for Raspberry Pi 3, no file copied."
fi
# copy fw
if [ -d /usr/share/bcm283x-firmware ]; then
        cp -rfp /usr/share/bcm283x-firmware/*.{bin,dat,elf} /boot/fw/
else
        echo "Missing bcm283x-firmware, no files copied."
fi
umount /boot/fw
echo 
echo "== Complete!"
echo

