#!/bin/bash

# ensure sudo user
if [ "$(whoami)" != "root" ] ; then
        echo "Error: This script requires 'sudo' privileges in order to write to disk & mount media."
        exit 1
fi

echo
echo "= This will update U-Boot and the "
echo "= Raspberry Pi Firmware to the latest."
UBOOT=$(rpm -q uboot-images-armv7)
FW=$(rpm -q bcm283x-firmware)
echo
echo "= Uboot: $UBOOT"
echo "= Firmware: $FW"
if [ -d /boot/fw ]; then
        	mount /dev/mmcblk0p1 /boot/fw
        else
        	mkdir /boot/fw
        	mount /dev/mmcblk0p1 /boot/fw
fi
# copy uboot
if [ -f /usr/share/uboot/rpi_2/u-boot.bin ]; then
        cp -rp /usr/share/uboot/rpi_2/u-boot.bin /boot/fw/rpi2-u-boot.bin
        else
        echo "Missing U-Boot for Raspberry Pi 2, no file copied."
fi
if [ -f /usr/share/uboot/rpi_3_32b/u-boot.bin ]; then
        cp -rp /usr/share/uboot/rpi_3_32b/u-boot.bin /boot/fw/rpi3-u-boot.bin
        else
        echo "Missing U-Boot for Raspberry Pi 3, no file copied."
fi
# copy fw
cp -rfp /usr/share/bcm283x-firmware/*.{bin,dat,elf} /boot/fw/
umount /boot/fw
echo 
echo "== Complete!"
echo

